# Generated by Django 4.2 on 2025-02-10 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="previous_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="previous_time",
        ),
        migrations.RemoveField(
            model_name="service",
            name="employee",
        ),
        migrations.AddField(
            model_name="service",
            name="employees",
            field=models.ManyToManyField(related_name="services", to="core.employee"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="core.customer",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="ending_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="qr_code",
            field=models.ImageField(null=True, upload_to="appointment_qrcodes/"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="starting_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="to_business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
    ]
