# Generated by Django 4.2 on 2025-02-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_appointmentslot_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="is_blocked",
            new_name="is_verified",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_number",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="booking_fee",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="cancellation_fee",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="ending_time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="previous_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="previous_time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="qr_code",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="reason_for_appointment",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="rescheduled_from",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="starting_time",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.appointmentslot",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="subscription",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="core.employee",
            ),
        ),
    ]
