# Generated by Django 4.2 on 2025-02-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_is_blocked_business_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentslot",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="core.business",
            ),
        ),
    ]
