# Generated by Django 4.2 on 2025-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_category_business_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("card", "Card"), ("cash", "Cash"), ("mobile", "Mobile")],
                default="card",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("ETB", "ETB"), ("USD", "USD")], default="ETB", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="currency",
            field=models.CharField(
                choices=[("ETB", "ETB"), ("USD", "USD")], default="ETB", max_length=3
            ),
        ),
    ]
