# Generated by Django 4.2 on 2025-02-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_appointment_notes_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="preliminary_answers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="preliminary_questions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="preliminary_questions_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("choice", "Choice"),
                    ("boolean", "Boolean"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
