# Generated by Django 4.2 on 2025-02-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="service",
            name="employee",
        ),
        migrations.AddField(
            model_name="service",
            name="employee",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="services", to="core.employee"
            ),
        ),
    ]
