# Generated by Django 4.2 on 2025-02-15 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_category_options_remove_service_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentslot",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
