# Generated by Django 4.2 on 2025-02-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_businesshour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointmentslot",
            old_name="is_available",
            new_name="is_reserved",
        ),
    ]
