# Generated by Django 4.2 on 2025-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_is_available_appointmentslot_is_reserved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="employee",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="core.employee"
            ),
        ),
    ]
