# Generated by Django 4.2 on 2025-02-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_businesshour_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="core.service",
            ),
        ),
    ]
