# Generated by Django 4.2 on 2025-02-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_rating_business_alter_rating_employee_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AppointmentSlot",
            new_name="ReservedSlot",
        ),
    ]
