# Generated by Django 4.2 on 2025-02-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_appointmentslot_reservedslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
