# Generated by Django 4.2 on 2025-02-21 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_service_created_at_service_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
