# Generated by Django 4.2 on 2025-02-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_employee_created_at_employee_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
