# Generated by Django 4.2 on 2025-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
