# Generated by Django 4.2 on 2025-02-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_appointment_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={
                (
                    "to_business",
                    "full_name",
                    "phone_number",
                    "address",
                    "id_number",
                    "user",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="reservedslot",
            unique_together={
                ("business", "service", "start_time", "end_time", "employee")
            },
        ),
    ]
