# Generated by Django 4.2 on 2025-02-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_customer_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("to_business", "full_name")},
        ),
    ]
