# Generated by Django 4.2 on 2025-02-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_customer_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("to_business", "id_number", "phone_number")},
        ),
    ]
