# Generated by Django 4.2 on 2025-02-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_customer_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("to_business", "id_number", "full_name")},
        ),
    ]
