# Generated by Django 4.2 on 2025-02-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_customer_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="businesshour",
            unique_together={("business", "day")},
        ),
    ]
