# Generated by Django 4.2 on 2025-03-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_business_email_alter_business_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="core.customer",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.reservedslot",
            ),
        ),
    ]
