# Generated by Django 4.2 on 2025-03-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_reservedslot_created_at_reservedslot_updated_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservedslot",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="reservedslot",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_slots",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="reservedslot",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_slots",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="reservedslot",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_slots",
                to="core.service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reservedslot",
            unique_together={
                (
                    "business",
                    "service",
                    "employee",
                    "start_time",
                    "end_time",
                    "is_reserved",
                )
            },
        ),
    ]
