# Generated by Django 4.2 on 2025-03-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_reservedslot_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("phone_number", "id_number", "full_name")},
        ),
    ]
