# Generated by Django 4.2 on 2025-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_customer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("undefined", "Unknown")],
                default="undefined",
                max_length=9,
            ),
        ),
    ]
