# Generated by Django 4.2 on 2025-03-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_category_is_active_alter_customer_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id_number",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="reservedslot",
            name="is_reserved",
            field=models.BooleanField(default=False),
        ),
    ]
